/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.qlns.view.task;

import com.qlns.dao.EmployeeDao;
import com.qlns.dao.TaskDao;
import com.qlns.model.Employee;
import com.qlns.model.Task;
import com.qlns.view.Main;
import com.qlns.view.employee.EmployeeComboboxModel;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTable;

public class TaskView extends javax.swing.JPanel {

	private Main main;
	private TaskTableModel ttm;
	private EmployeeComboboxModel ecm;

	private void reloadTable() {
		reloadTable(TaskDao.findAll());
	}

	private void reloadTable(List<Task> tasks) {
		ttm = new TaskTableModel(tasks);
		table.setModel(ttm);
		table.repaint();
	}

	private void loadCombobox() {
		loadCombobox(null);
	}

	private void loadCombobox(Employee e) {
		ecm = new EmployeeComboboxModel(EmployeeDao.findAll());
		ecm.setSelectedItem(e);
		if (e != null) {
			cbb.setModel(ecm);
		}
		cbb.repaint();
	}

	/**
	 * Creates new form TaskView
	 */
	public TaskView(Main main) {
		this.main = main;
		initComponents();
		reloadTable();
		loadCombobox();
	}

	/**
	 * This method is called from within the constructor to initialize the
	 * form. WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                completedGroup = new javax.swing.ButtonGroup();
                jScrollPane1 = new javax.swing.JScrollPane();
                table = new javax.swing.JTable();
                jLabel1 = new javax.swing.JLabel();
                jLabel2 = new javax.swing.JLabel();
                lbID = new javax.swing.JLabel();
                jLabel3 = new javax.swing.JLabel();
                jScrollPane2 = new javax.swing.JScrollPane();
                taDesc = new javax.swing.JTextArea();
                tfName = new javax.swing.JTextField();
                jLabel4 = new javax.swing.JLabel();
                jLabel5 = new javax.swing.JLabel();
                cbb = new javax.swing.JComboBox<>();
                lbCompleted = new javax.swing.JLabel();
                btnAdd = new javax.swing.JButton();
                btnUpdate = new javax.swing.JButton();
                btnDelete = new javax.swing.JButton();
                rbYes = new javax.swing.JRadioButton();
                rbNo = new javax.swing.JRadioButton();
                dcDeadline = new com.toedter.calendar.JDateChooser();

                table.setModel(new javax.swing.table.DefaultTableModel(
                        new Object [][] {
                                {null, null, null, null},
                                {null, null, null, null},
                                {null, null, null, null},
                                {null, null, null, null}
                        },
                        new String [] {
                                "Title 1", "Title 2", "Title 3", "Title 4"
                        }
                ));
                table.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                tableMouseClicked(evt);
                        }
                });
                jScrollPane1.setViewportView(table);

                jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
                jLabel1.setText("Quản lý công việc");

                jLabel2.setText("Tên");

                lbID.setText("ID");

                jLabel3.setText("Mô tả");

                taDesc.setColumns(20);
                taDesc.setRows(5);
                jScrollPane2.setViewportView(taDesc);

                jLabel4.setText("Hạn");

                jLabel5.setText("Nhân viên");

                lbCompleted.setText("Hoàn thành:");

                btnAdd.setText("Thêm");
                btnAdd.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnAddActionPerformed(evt);
                        }
                });

                btnUpdate.setText("Cập nhật");
                btnUpdate.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnUpdateActionPerformed(evt);
                        }
                });

                btnDelete.setText("Xóa");
                btnDelete.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnDeleteActionPerformed(evt);
                        }
                });

                completedGroup.add(rbYes);
                rbYes.setText("Đã hoàn thành");

                completedGroup.add(rbNo);
                rbNo.setText("Chưa hoàn thành");

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
                this.setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGap(32, 32, 32)
                                                                .addComponent(btnAdd)
                                                                .addGap(35, 35, 35)
                                                                .addComponent(btnUpdate)
                                                                .addGap(43, 43, 43)
                                                                .addComponent(btnDelete)
                                                                .addGap(27, 27, 27))
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                                .addContainerGap()
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(lbCompleted)
                                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                                .addComponent(jLabel2)
                                                                                .addComponent(lbID)
                                                                                .addComponent(jLabel3)
                                                                                .addComponent(jLabel5)
                                                                                .addComponent(jLabel4)
                                                                                .addComponent(jScrollPane2)
                                                                                .addComponent(cbb, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                                .addComponent(tfName)
                                                                                .addComponent(dcDeadline, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                        .addGroup(layout.createSequentialGroup()
                                                                                .addComponent(rbYes)
                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                                .addComponent(rbNo)))
                                                                .addGap(59, 59, 59)))
                                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 681, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(470, 470, 470)
                                                .addComponent(jLabel1)))
                                .addContainerGap(40, Short.MAX_VALUE))
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(jLabel1)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(20, 20, 20)
                                                .addComponent(lbID)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel2)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(tfName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(2, 2, 2)
                                                .addComponent(jLabel3)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel4)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(dcDeadline, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel5)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(cbb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(13, 13, 13)
                                                .addComponent(lbCompleted)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(rbYes)
                                                        .addComponent(rbNo))
                                                .addGap(34, 34, 34)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(btnAdd)
                                                        .addComponent(btnUpdate)
                                                        .addComponent(btnDelete))
                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(77, 77, 77))))
                );
        }// </editor-fold>//GEN-END:initComponents

        private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
		try {
			String name = tfName.getText(), description = taDesc.getText();
			Date deadline = dcDeadline.getDate();
			Employee e = (Employee) cbb.getSelectedItem();
			Boolean completed = rbYes.isSelected();
			if (TaskDao.create(new Task(name, description, deadline, e, completed))) {
				JOptionPane.showMessageDialog(null, "Thêm thành công");
				reloadTable();
				return;
			}
			JOptionPane.showMessageDialog(null, "Thêm thất bại");
		} catch (Exception e) {
			JOptionPane.showMessageDialog(null, "Vui lòng chọn một công việc và nhập thông tin hợp lệ");
		}
        }//GEN-LAST:event_btnAddActionPerformed

        private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
		try {
			JTable source = (JTable) evt.getSource();
			int row = source.rowAtPoint(evt.getPoint());
			Task t = ttm.getRow(row);
			ttm.setSelectedRow(t);
			lbID.setText("ID: " + t.getId());
			tfName.setText(t.getName());
			dcDeadline.setDate(t.getDeadline());
			taDesc.setText(t.getDescription());
			loadCombobox(t.getEmployee());
			completedGroup.clearSelection();
			if (t.getCompleted()) {
				rbYes.setSelected(true);
			} else {
				rbNo.setSelected(true);
			}
		} catch (Exception e) {

		}
        }//GEN-LAST:event_tableMouseClicked

        private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
		try {
			// lay ra cong viec da chon
			Task t = ttm.getSelectedRow();
			String name = tfName.getText(), description = taDesc.getText();
			Date deadline = dcDeadline.getDate();
			Employee e = (Employee) cbb.getSelectedItem();
			Boolean completed = rbYes.isSelected();
			Task taskUpdate = new Task(name, description, deadline, e, completed);
			taskUpdate.setId(t.getId());
			if (TaskDao.update(taskUpdate)) {
				JOptionPane.showMessageDialog(null, "Cập nhật thành công");
				reloadTable();
				return;
			}
			JOptionPane.showMessageDialog(null, "Cập nhật thất bại");
		} catch (Exception e) {
			e.printStackTrace();
			JOptionPane.showMessageDialog(null, "Vui lòng chọn một công việc và nhập thông tin hợp lệ");
		}

        }//GEN-LAST:event_btnUpdateActionPerformed

        private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
		try {
			Task t = ttm.getSelectedRow();
			if (TaskDao.delete(t.getId())) {
				JOptionPane.showMessageDialog(null, "Xóa thành công");
				reloadTable();
				return;
			}
			JOptionPane.showMessageDialog(null, "Xóa thất bại");
		} catch(Exception e){
			JOptionPane.showMessageDialog(null, "Vui lòng chọn một công việc và nhập thông tin hợp lệ");
		}
        }//GEN-LAST:event_btnDeleteActionPerformed


        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton btnAdd;
        private javax.swing.JButton btnDelete;
        private javax.swing.JButton btnUpdate;
        private javax.swing.JComboBox<com.qlns.model.Employee> cbb;
        private javax.swing.ButtonGroup completedGroup;
        private com.toedter.calendar.JDateChooser dcDeadline;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JLabel jLabel2;
        private javax.swing.JLabel jLabel3;
        private javax.swing.JLabel jLabel4;
        private javax.swing.JLabel jLabel5;
        private javax.swing.JScrollPane jScrollPane1;
        private javax.swing.JScrollPane jScrollPane2;
        private javax.swing.JLabel lbCompleted;
        private javax.swing.JLabel lbID;
        private javax.swing.JRadioButton rbNo;
        private javax.swing.JRadioButton rbYes;
        private javax.swing.JTextArea taDesc;
        private javax.swing.JTable table;
        private javax.swing.JTextField tfName;
        // End of variables declaration//GEN-END:variables
}
