/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.qlns.view.employee_log;

import com.qlns.dao.EmployeeDao;
import com.qlns.dao.EmployeeLogDao;
import com.qlns.model.Employee;
import com.qlns.model.EmployeeLog;
import com.qlns.view.Main;
import com.qlns.view.employee.EmployeeComboboxModel;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTable;

public class EmployeeLogView extends javax.swing.JPanel {

	private Main main;
	private EmployeeLogTableModel eltm;
	private EmployeeComboboxModel ecm;

	private void reloadTable() {
		reloadTable(EmployeeLogDao.findAll());
	}

	private void reloadTable(List<EmployeeLog> elList) {
		eltm = new EmployeeLogTableModel(elList);
		table.setModel(eltm);
		table.repaint();
	}

	private void reloadCbb() {
		reloadCbb(null);
	}

	private void reloadCbb(Employee e) {
		ecm = new EmployeeComboboxModel(EmployeeDao.findAll());
		if (e != null) {
			ecm.setSelectedItem(e);
		}
		cbEmployee.setModel(ecm);
		cbEmployee.repaint();
	}

	/**
	 * Creates new form EmployeeLogView
	 */
	public EmployeeLogView(Main main) {
		this.main = main;
		initComponents();
		reloadTable();
		rbYes.setSelected(true);
		reloadCbb();
	}

	/**
	 * This method is called from within the constructor to initialize the
	 * form. WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                bgReward = new javax.swing.ButtonGroup();
                jLabel1 = new javax.swing.JLabel();
                jScrollPane1 = new javax.swing.JScrollPane();
                table = new javax.swing.JTable();
                lbID = new javax.swing.JLabel();
                jLabel2 = new javax.swing.JLabel();
                cbEmployee = new javax.swing.JComboBox<>();
                jLabel3 = new javax.swing.JLabel();
                tfAmount = new javax.swing.JTextField();
                jLabel4 = new javax.swing.JLabel();
                rbYes = new javax.swing.JRadioButton();
                rbNo = new javax.swing.JRadioButton();
                jLabel5 = new javax.swing.JLabel();
                jScrollPane2 = new javax.swing.JScrollPane();
                taReason = new javax.swing.JTextArea();
                btnAdd = new javax.swing.JButton();
                btnUpdate = new javax.swing.JButton();
                btnDelete = new javax.swing.JButton();

                jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
                jLabel1.setText("Thưởng phạt");

                jScrollPane1.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                jScrollPane1MouseClicked(evt);
                        }
                });

                table.setModel(new javax.swing.table.DefaultTableModel(
                        new Object [][] {
                                {null, null, null, null},
                                {null, null, null, null},
                                {null, null, null, null},
                                {null, null, null, null}
                        },
                        new String [] {
                                "Title 1", "Title 2", "Title 3", "Title 4"
                        }
                ));
                table.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                tableMouseClicked(evt);
                        }
                });
                jScrollPane1.setViewportView(table);

                lbID.setText("ID");

                jLabel2.setText("Nhân viên");

                jLabel3.setText("Số tiền");

                jLabel4.setText("Loại");

                bgReward.add(rbYes);
                rbYes.setText("Thưởng");
                rbYes.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                rbYesActionPerformed(evt);
                        }
                });

                bgReward.add(rbNo);
                rbNo.setText("Phạt");

                jLabel5.setText("Lý do");

                taReason.setColumns(20);
                taReason.setRows(5);
                jScrollPane2.setViewportView(taReason);

                btnAdd.setText("Thêm");
                btnAdd.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnAddActionPerformed(evt);
                        }
                });

                btnUpdate.setText("Cập nhật");
                btnUpdate.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnUpdateActionPerformed(evt);
                        }
                });

                btnDelete.setText("Xóa");
                btnDelete.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnDeleteActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
                this.setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(525, 525, 525)
                                .addComponent(jLabel1)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(tfAmount)
                                                        .addComponent(cbEmployee, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(lbID)
                                                                        .addComponent(jLabel2)
                                                                        .addComponent(jLabel3)
                                                                        .addComponent(jLabel4)
                                                                        .addGroup(layout.createSequentialGroup()
                                                                                .addComponent(rbYes)
                                                                                .addGap(18, 18, 18)
                                                                                .addComponent(rbNo))
                                                                        .addComponent(jLabel5)
                                                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGap(0, 0, Short.MAX_VALUE)))
                                                .addGap(40, 40, 40))
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(btnAdd)
                                                .addGap(27, 27, 27)
                                                .addComponent(btnUpdate)
                                                .addGap(28, 28, 28)
                                                .addComponent(btnDelete)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 123, Short.MAX_VALUE)))
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 722, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29))
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(lbID)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jLabel2)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(cbEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel3)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(tfAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel4)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(rbYes)
                                                        .addComponent(rbNo))
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel5)
                                                .addGap(18, 18, 18)
                                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(btnAdd)
                                                        .addComponent(btnUpdate)
                                                        .addComponent(btnDelete))))
                                .addContainerGap(124, Short.MAX_VALUE))
                );
        }// </editor-fold>//GEN-END:initComponents

        private void rbYesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbYesActionPerformed
		// TODO add your handling code here:
        }//GEN-LAST:event_rbYesActionPerformed

        private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
		try {
			String reason = taReason.getText();
			Employee e = (Employee) cbEmployee.getSelectedItem();
			Boolean reward = rbYes.isSelected();
			Long amount = Long.parseLong(tfAmount.getText());
			System.out.println(e);
			if (EmployeeLogDao.create(new EmployeeLog(e, reward, amount, reason))) {
				JOptionPane.showMessageDialog(null, "Thêm thành công");
				reloadTable();
				return;
			}
			JOptionPane.showMessageDialog(null, "Thêm thất bại");
		} catch (Exception e) {
			JOptionPane.showMessageDialog(null, "Vui lòng nhập thông tin chính xác");
		}
        }//GEN-LAST:event_btnAddActionPerformed

        private void jScrollPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane1MouseClicked
		// TODO add your handling code here:
        }//GEN-LAST:event_jScrollPane1MouseClicked

        private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
		try {
			JTable source = (JTable) evt.getSource();
			int row = source.rowAtPoint(evt.getPoint());
			EmployeeLog el = eltm.getRow(row);
			eltm.setSelectedRow(el);

			reloadCbb(el.getEmployee());
			taReason.setText(el.getReason());
			bgReward.clearSelection();
			lbID.setText("ID: " + el.getId());
			if (el.getReward()) {
				rbYes.setSelected(true);
			} else {
				rbNo.setSelected(true);
			}
			tfAmount.setText(el.getAmount() + "");
		} catch (Exception e) {

		}
        }//GEN-LAST:event_tableMouseClicked

        private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
		try {
			EmployeeLog el = eltm.getSelectedRow();
			String reason = taReason.getText();
			Employee e = (Employee) cbEmployee.getSelectedItem();
			Boolean reward = rbYes.isSelected();
			Long amount = Long.parseLong(tfAmount.getText());
			EmployeeLog elUpdate = new EmployeeLog(e, reward, amount, reason);
			elUpdate.setId(el.getId());
			if (EmployeeLogDao.update(elUpdate)) {
				JOptionPane.showMessageDialog(null, "Cập nhật thành công");
				reloadTable();
				return;
			}
			JOptionPane.showMessageDialog(null, "Cập nhật thất bại");

		} catch (Exception e) {
			JOptionPane.showMessageDialog(null, "Vui lòng chọn một hàng và điền thông tin hợp lệ!");
		}
        }//GEN-LAST:event_btnUpdateActionPerformed

        private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
		try {
			EmployeeLog el = eltm.getSelectedRow();
			if (EmployeeLogDao.delete(el.getId())) {
				JOptionPane.showMessageDialog(null, "Xóa thành công");
				reloadTable();
				return;
			}
			JOptionPane.showMessageDialog(null, "Xóa thất bại");
		} catch (Exception e) {
			JOptionPane.showMessageDialog(null, "Vui lòng chọn một hàng!");
		}
        }//GEN-LAST:event_btnDeleteActionPerformed


        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.ButtonGroup bgReward;
        private javax.swing.JButton btnAdd;
        private javax.swing.JButton btnDelete;
        private javax.swing.JButton btnUpdate;
        private javax.swing.JComboBox<com.qlns.model.Employee> cbEmployee;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JLabel jLabel2;
        private javax.swing.JLabel jLabel3;
        private javax.swing.JLabel jLabel4;
        private javax.swing.JLabel jLabel5;
        private javax.swing.JScrollPane jScrollPane1;
        private javax.swing.JScrollPane jScrollPane2;
        private javax.swing.JLabel lbID;
        private javax.swing.JRadioButton rbNo;
        private javax.swing.JRadioButton rbYes;
        private javax.swing.JTextArea taReason;
        private javax.swing.JTable table;
        private javax.swing.JTextField tfAmount;
        // End of variables declaration//GEN-END:variables
}
