/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.qlns.view.employee;

import com.qlns.dao.EmployeeDao;
import com.qlns.dao.EmployeeLogDao;
import com.qlns.dao.SalaryLogDao;
import com.qlns.model.Employee;
import com.qlns.model.EmployeeLog;
import com.qlns.model.SalaryLog;
import com.qlns.view.Main;
import java.awt.HeadlessException;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTable;

public class EmployeeView extends javax.swing.JPanel {

	private Main main;
	private EmployeeTableModel etm;

	/**
	 * Creates new form EmployeeView
	 */
	public EmployeeView(Main main) {
		this.main = main;
		main.showMenuBar();
		initComponents();
		reloadTable();
	}

	private void reloadTable() {
		reloadTable(EmployeeDao.findAll());
	}

	private void reloadTable(List<Employee> employees) {
		etm = new EmployeeTableModel(employees);
		table.setModel(etm);
		table.repaint();
	}

	/**
	 * This method is called from within the constructor to initialize the
	 * form. WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                genderGroup = new javax.swing.ButtonGroup();
                jLabel1 = new javax.swing.JLabel();
                jScrollPane1 = new javax.swing.JScrollPane();
                table = new javax.swing.JTable();
                jLabel2 = new javax.swing.JLabel();
                jLabel3 = new javax.swing.JLabel();
                jLabel4 = new javax.swing.JLabel();
                jLabel5 = new javax.swing.JLabel();
                jLabel6 = new javax.swing.JLabel();
                tfFirstName = new javax.swing.JTextField();
                tfLastName = new javax.swing.JTextField();
                tfPhoneNumber = new javax.swing.JTextField();
                tfAddress = new javax.swing.JTextField();
                tfSalary = new javax.swing.JTextField();
                lbID = new javax.swing.JLabel();
                btnAdd = new javax.swing.JButton();
                btnEdit = new javax.swing.JButton();
                btnDelete = new javax.swing.JButton();
                tfSearch = new javax.swing.JTextField();
                btnSearch = new javax.swing.JButton();
                btnRefresh = new javax.swing.JButton();
                jLabel7 = new javax.swing.JLabel();
                rbMale = new javax.swing.JRadioButton();
                rbFemale = new javax.swing.JRadioButton();
                btnPay = new javax.swing.JButton();

                jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
                jLabel1.setText("Quản lý nhân viên");

                table.setModel(new javax.swing.table.DefaultTableModel(
                        new Object [][] {
                                {null, null, null, null},
                                {null, null, null, null},
                                {null, null, null, null},
                                {null, null, null, null}
                        },
                        new String [] {
                                "Title 1", "Title 2", "Title 3", "Title 4"
                        }
                ));
                table.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                tableMouseClicked(evt);
                        }
                });
                jScrollPane1.setViewportView(table);

                jLabel2.setText("Tên");

                jLabel3.setText("Họ đệm");

                jLabel4.setText("SĐT");

                jLabel5.setText("Địa chỉ");

                jLabel6.setText("Lương");

                tfFirstName.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                tfFirstNameActionPerformed(evt);
                        }
                });

                lbID.setText("ID");

                btnAdd.setText("Thêm");
                btnAdd.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnAddActionPerformed(evt);
                        }
                });

                btnEdit.setText("Sửa");
                btnEdit.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnEditActionPerformed(evt);
                        }
                });

                btnDelete.setText("Xóa");
                btnDelete.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnDeleteActionPerformed(evt);
                        }
                });

                btnSearch.setText("Tìm");
                btnSearch.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnSearchActionPerformed(evt);
                        }
                });

                btnRefresh.setText("Làm mới");
                btnRefresh.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnRefreshActionPerformed(evt);
                        }
                });

                jLabel7.setText("Giới tính");

                genderGroup.add(rbMale);
                rbMale.setText("Male");

                genderGroup.add(rbFemale);
                rbFemale.setText("Female");
                rbFemale.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                rbFemaleActionPerformed(evt);
                        }
                });

                btnPay.setText("Trả lương");
                btnPay.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnPayActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
                this.setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(42, 301, Short.MAX_VALUE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 681, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(46, 46, 46))
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(345, 345, 345)
                                                .addComponent(jLabel1))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(59, 59, 59)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addComponent(lbID)
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                        .addComponent(jLabel2)
                                                                        .addComponent(jLabel3)
                                                                        .addComponent(jLabel4)
                                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                .addComponent(jLabel6)
                                                                                .addComponent(jLabel5))
                                                                        .addComponent(tfAddress)
                                                                        .addComponent(tfPhoneNumber)
                                                                        .addComponent(tfLastName)
                                                                        .addComponent(tfFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                                        .addGap(2, 2, 2)
                                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addComponent(jLabel7)
                                                                                .addComponent(tfSalary, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                                                .addComponent(btnAdd)
                                                                                .addGap(37, 37, 37))
                                                                        .addGroup(layout.createSequentialGroup()
                                                                                .addComponent(rbMale)
                                                                                .addGap(60, 60, 60)))
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(rbFemale)
                                                                        .addComponent(btnEdit))
                                                                .addGap(34, 34, 34)
                                                                .addComponent(btnDelete)
                                                                .addGap(35, 35, 35)
                                                                .addComponent(btnPay)
                                                                .addGap(44, 44, 44)
                                                                .addComponent(tfSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(27, 27, 27)
                                                                .addComponent(btnSearch)
                                                                .addGap(74, 74, 74)
                                                                .addComponent(btnRefresh)))))
                                .addContainerGap(84, Short.MAX_VALUE))
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel1)
                                                .addGap(36, 36, 36)
                                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(lbID)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jLabel2)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(tfFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel3)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(tfLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(1, 1, 1)
                                                .addComponent(jLabel4)
                                                .addGap(10, 10, 10)
                                                .addComponent(tfPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel5)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(tfAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(8, 8, 8)
                                                .addComponent(jLabel6)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(tfSalary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel7)
                                .addGap(2, 2, 2)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(rbFemale, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(rbMale))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(btnAdd)
                                                .addComponent(btnEdit)
                                                .addComponent(btnDelete)
                                                .addComponent(btnPay))
                                        .addComponent(tfSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(btnSearch)
                                                .addComponent(btnRefresh)))
                                .addContainerGap(147, Short.MAX_VALUE))
                );
        }// </editor-fold>//GEN-END:initComponents

        private void tfFirstNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfFirstNameActionPerformed
		// TODO add your handling code here:
        }//GEN-LAST:event_tfFirstNameActionPerformed

        private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
		String firstName, lastName, phoneNumber, address;
		Long salary = 0L;
		try {
			firstName = tfFirstName.getText();
			if (firstName.equals("")) {
				JOptionPane.showMessageDialog(null, "Vui lòng nhập tên");
				return;
			}
			lastName = tfLastName.getText();
			if (lastName.equals("")) {
				JOptionPane.showMessageDialog(null, "Vui lòng nhập họ");
				return;
			}
			phoneNumber = tfPhoneNumber.getText();
			if (phoneNumber.equals("")) {
				JOptionPane.showMessageDialog(null, "Vui lòng nhập số điện thoại");
				return;
			}
			address = tfAddress.getText();
			if (phoneNumber.equals("")) {
				JOptionPane.showMessageDialog(null, "Vui lòng nhập số địa chỉ");
				return;
			}
			salary = Long.parseLong(tfSalary.getText());
			Boolean gender = rbMale.isSelected();
			if (EmployeeDao.create(new Employee(firstName, lastName, phoneNumber, address, salary, gender))) {
				JOptionPane.showMessageDialog(null, "Thêm thành công");
				reloadTable();
				return;
			}

		} catch (HeadlessException | NumberFormatException e) {
			JOptionPane.showMessageDialog(null, "Vui lòng nhập lương hợp lệ");
			return;
		}

		JOptionPane.showMessageDialog(null, "Thêm thất bại");
        }//GEN-LAST:event_btnAddActionPerformed

        private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
		try {
			Employee e = etm.getSelectedRow();
			String firstName, lastName, phoneNumber, address;
			Long salary = 0L;
			firstName = tfFirstName.getText();
			if (firstName.equals("")) {
				JOptionPane.showMessageDialog(null, "Vui lòng nhập tên");
				return;
			}
			lastName = tfLastName.getText();
			if (lastName.equals("")) {
				JOptionPane.showMessageDialog(null, "Vui lòng nhập họ");
				return;
			}
			phoneNumber = tfPhoneNumber.getText();
			if (phoneNumber.equals("")) {
				JOptionPane.showMessageDialog(null, "Vui lòng nhập số điện thoại");
				return;
			}
			address = tfAddress.getText();
			if (phoneNumber.equals("")) {
				JOptionPane.showMessageDialog(null, "Vui lòng nhập số địa chỉ");
				return;
			}

			salary = Long.parseLong(tfSalary.getText());
			e.setFirstName(firstName);
			e.setLastName(lastName);
			e.setAddress(address);
			e.setPhoneNumber(phoneNumber);
			e.setSalary(salary);
			e.setGender(rbMale.isSelected());
			System.out.println(e.getGender());

			if (EmployeeDao.update(e)) {
				JOptionPane.showMessageDialog(null, "Cập nhật thành công");
				reloadTable();
				return;
			}

			JOptionPane.showMessageDialog(null, "Cập nhật thất bại");
		} catch (Exception e) {
			e.printStackTrace();
			JOptionPane.showMessageDialog(null, "Vui lòng chọn một nhân viên");
		}
        }//GEN-LAST:event_btnEditActionPerformed

        private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
		try {
			JTable source = (JTable) evt.getSource();
			int row = source.rowAtPoint(evt.getPoint());
			Employee e = etm.getRow(row);
			etm.setSelectedRow(e);
			lbID.setText("ID: " + e.getId());
			tfFirstName.setText(e.getFirstName());
			tfLastName.setText(e.getLastName());
			tfAddress.setText(e.getAddress());
			tfPhoneNumber.setText(e.getPhoneNumber());
			tfSalary.setText(e.getSalary() + "");
			genderGroup.clearSelection();
			if (e.getGender()) {
				rbMale.setSelected(true);
			} else {
				rbFemale.setSelected(true);
			}
		} catch (Exception e) {
			e.printStackTrace();
		}
        }//GEN-LAST:event_tableMouseClicked

        private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
		reloadTable();
        }//GEN-LAST:event_btnRefreshActionPerformed

        private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
		// TODO add your handling code here:
		try {

			Employee e = etm.getRow(table.getSelectedColumn());
			if (EmployeeDao.delete(e.getId())) {
				JOptionPane.showMessageDialog(null, "Xóa thành công");
				reloadTable();
				return;
			}
			JOptionPane.showMessageDialog(null, "Xóa thất bại");
		} catch (Exception e) {
			JOptionPane.showMessageDialog(null, "Vui lòng chọn một nhân viên");
		}
        }//GEN-LAST:event_btnDeleteActionPerformed

        private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
		String name = tfSearch.getText();
		reloadTable(EmployeeDao.findByName(name));
        }//GEN-LAST:event_btnSearchActionPerformed

        private void rbFemaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbFemaleActionPerformed
		// TODO add your handling code here:
        }//GEN-LAST:event_rbFemaleActionPerformed

        private void btnPayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPayActionPerformed
		try {
			Employee e = etm.getSelectedRow();
			System.out.println(e);

			if (SalaryLogDao.isPaid(e.getId())) {
				JOptionPane.showMessageDialog(null, "Đã trả lương tháng này!");
				return;
			}
			List<EmployeeLog> elList = EmployeeLogDao.findInMonthOfEmployee(e.getId());
			Long realSalary = e.getSalary();
			for (EmployeeLog el : elList) {
				if (el.getReward()) {
					realSalary += el.getAmount();
				} else {
					realSalary -= el.getAmount();
				}
			}
			if (SalaryLogDao.create(new SalaryLog(e, realSalary))) {
				JOptionPane.showMessageDialog(null, "Trả hoàn thất");
				reloadTable();
				return;
			}
			JOptionPane.showMessageDialog(null, "Trả thất bại");

		} catch (Exception e) {
			JOptionPane.showMessageDialog(null, "Vui lòng chọn một nhân viên");
		}
        }//GEN-LAST:event_btnPayActionPerformed


        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton btnAdd;
        private javax.swing.JButton btnDelete;
        private javax.swing.JButton btnEdit;
        private javax.swing.JButton btnPay;
        private javax.swing.JButton btnRefresh;
        private javax.swing.JButton btnSearch;
        private javax.swing.ButtonGroup genderGroup;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JLabel jLabel2;
        private javax.swing.JLabel jLabel3;
        private javax.swing.JLabel jLabel4;
        private javax.swing.JLabel jLabel5;
        private javax.swing.JLabel jLabel6;
        private javax.swing.JLabel jLabel7;
        private javax.swing.JScrollPane jScrollPane1;
        private javax.swing.JLabel lbID;
        private javax.swing.JRadioButton rbFemale;
        private javax.swing.JRadioButton rbMale;
        private javax.swing.JTable table;
        private javax.swing.JTextField tfAddress;
        private javax.swing.JTextField tfFirstName;
        private javax.swing.JTextField tfLastName;
        private javax.swing.JTextField tfPhoneNumber;
        private javax.swing.JTextField tfSalary;
        private javax.swing.JTextField tfSearch;
        // End of variables declaration//GEN-END:variables
}
